#
# test-builds.yml
# Do test builds to catch compile errors
#

name: CI

on:
  push:
    branches:
    - Marlin_FB_Reborn_2.0.9.3
    paths-ignore:
    - config/**
    - data/**
    - docs/**
    - '**/*.md'

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-platform:
        - mks_robin_nano_v1_3_f4_x32_nefelim4ag
        - mks_robin_nano_v1_3_f4_x32
        - mks_robin_nano_Sv1_3_f4_x16
        - mks_robin_nano_Sv1_3_f4_x16_SWAP_Z_E_TSensor_5
        - mks_robin_nano35_x32
        - mks_robin_nano35_x16

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Select Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install PlatformIO
      run: |
        pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
        platformio update

    - name: Run ${{ matrix.test-platform }}
      run: |
        pio run -e ${{ matrix.test-platform }}

    - uses: actions/upload-artifact@v2
      with:
        name: Firmware ${{ matrix.test-platform }}
        path: .pio/build/${{ matrix.test-platform }}/Robin_nano35.bin
